// AUTO-GENERATED — do not edit.
// Source: design/design-tokens.json
// Regenerate: python3 scripts/build_tokens.py --target dart
//
// Consume: ThemeData td = appThemeDataFor('clay');
// Direct token access: AppTokens t = Theme.of(context).extension<AppTokens>()!;

import 'dart:ui';
import 'package:flutter/material.dart';


class AppTokens extends ThemeExtension<AppTokens> {
  final Color brand;
  final Color brandHover;
  final Color brandPressed;
  final Color brandSoft;
  final Color brandContrast;
  final Color link;
  final Color bg;
  final Color bgInverse;
  final Color surface;
  final Color surface2;
  final Color surface3;
  final Color surface4;
  final Color surfaceInverse;
  final Color overlay;
  final Color overlaySoft;
  final Color glassNav;
  final Color textPrimary;
  final Color textSecondary;
  final Color textMuted;
  final Color textDisabled;
  final Color textInverse;
  final Color border;
  final Color borderStrong;
  final Color borderBrand;
  final Color focus;
  final Color success;
  final Color successSoft;
  final Color warning;
  final Color warningSoft;
  final Color error;
  final Color errorSoft;
  final Color errorHover;
  final Color info;
  final Color infoSoft;
  final Color confidenceHigh;
  final Color confidenceMedium;
  final Color confidenceLow;
  final Color confidenceHighSoft;
  final Color confidenceMediumSoft;
  final Color confidenceLowSoft;
  final Color catGrocery;
  final Color catRestaurant;
  final Color catUtility;
  final Color catPersonalService;
  final Color catSubscription;
  final Color catOther;
  final double space0;
  final double space0_5;
  final double space1;
  final double space1_5;
  final double space2;
  final double space3;
  final double space4;
  final double space5;
  final double space6;
  final double space8;
  final double space10;
  final double space12;
  final double space16;
  final double space20;
  final double space24;
  final double space32;
  final double space40;
  final double space48;
  final double radiusV0;
  final double radiusXs;
  final double radiusSm;
  final double radiusMd;
  final double radiusLg;
  final double radiusXl;
  final double radiusPill;
  final double radiusFull;
  final double stroke0;
  final double stroke1;
  final double stroke2;
  final double stroke3;
  final List<BoxShadow> shadow0;
  final List<BoxShadow> shadow1;
  final List<BoxShadow> shadow2;
  final List<BoxShadow> shadow3;
  final List<BoxShadow> shadow4;
  final List<BoxShadow> shadow5;
  final Duration durationInstant;
  final Duration durationFast;
  final Duration durationBase;
  final Duration durationSlow;
  final Duration durationElaborate;
  final Curve easeStandard;
  final Curve easeOut;
  final Curve easeIn;
  final Curve easeInOut;
  final Curve easeSpring;
  final TextStyle typeHero;
  final TextStyle typeV4xl;
  final TextStyle typeV3xl;
  final TextStyle typeV2xl;
  final TextStyle typeXl;
  final TextStyle typeLg;
  final TextStyle typeLgreg;
  final TextStyle typeMd;
  final TextStyle typeBody;
  final TextStyle typeBodyem;
  final TextStyle typeSm;
  final TextStyle typeSmem;
  final TextStyle typeXs;
  final TextStyle typeXsem;
  final TextStyle typeNano;
  final String fontDisplay;
  final String fontText;
  final String fontMono;

  const AppTokens({
    required this.brand,
    required this.brandHover,
    required this.brandPressed,
    required this.brandSoft,
    required this.brandContrast,
    required this.link,
    required this.bg,
    required this.bgInverse,
    required this.surface,
    required this.surface2,
    required this.surface3,
    required this.surface4,
    required this.surfaceInverse,
    required this.overlay,
    required this.overlaySoft,
    required this.glassNav,
    required this.textPrimary,
    required this.textSecondary,
    required this.textMuted,
    required this.textDisabled,
    required this.textInverse,
    required this.border,
    required this.borderStrong,
    required this.borderBrand,
    required this.focus,
    required this.success,
    required this.successSoft,
    required this.warning,
    required this.warningSoft,
    required this.error,
    required this.errorSoft,
    required this.errorHover,
    required this.info,
    required this.infoSoft,
    required this.confidenceHigh,
    required this.confidenceMedium,
    required this.confidenceLow,
    required this.confidenceHighSoft,
    required this.confidenceMediumSoft,
    required this.confidenceLowSoft,
    required this.catGrocery,
    required this.catRestaurant,
    required this.catUtility,
    required this.catPersonalService,
    required this.catSubscription,
    required this.catOther,
    required this.space0,
    required this.space0_5,
    required this.space1,
    required this.space1_5,
    required this.space2,
    required this.space3,
    required this.space4,
    required this.space5,
    required this.space6,
    required this.space8,
    required this.space10,
    required this.space12,
    required this.space16,
    required this.space20,
    required this.space24,
    required this.space32,
    required this.space40,
    required this.space48,
    required this.radiusV0,
    required this.radiusXs,
    required this.radiusSm,
    required this.radiusMd,
    required this.radiusLg,
    required this.radiusXl,
    required this.radiusPill,
    required this.radiusFull,
    required this.stroke0,
    required this.stroke1,
    required this.stroke2,
    required this.stroke3,
    required this.shadow0,
    required this.shadow1,
    required this.shadow2,
    required this.shadow3,
    required this.shadow4,
    required this.shadow5,
    required this.durationInstant,
    required this.durationFast,
    required this.durationBase,
    required this.durationSlow,
    required this.durationElaborate,
    required this.easeStandard,
    required this.easeOut,
    required this.easeIn,
    required this.easeInOut,
    required this.easeSpring,
    required this.typeHero,
    required this.typeV4xl,
    required this.typeV3xl,
    required this.typeV2xl,
    required this.typeXl,
    required this.typeLg,
    required this.typeLgreg,
    required this.typeMd,
    required this.typeBody,
    required this.typeBodyem,
    required this.typeSm,
    required this.typeSmem,
    required this.typeXs,
    required this.typeXsem,
    required this.typeNano,
    required this.fontDisplay,
    required this.fontText,
    required this.fontMono,
  });

  @override
  AppTokens copyWith() => this;

  @override
  AppTokens lerp(ThemeExtension<AppTokens>? other, double t) {
    if (other is! AppTokens) return this;
    return AppTokens(
      brand: Color.lerp(brand, other.brand, t)!,
      brandHover: Color.lerp(brandHover, other.brandHover, t)!,
      brandPressed: Color.lerp(brandPressed, other.brandPressed, t)!,
      brandSoft: Color.lerp(brandSoft, other.brandSoft, t)!,
      brandContrast: Color.lerp(brandContrast, other.brandContrast, t)!,
      link: Color.lerp(link, other.link, t)!,
      bg: Color.lerp(bg, other.bg, t)!,
      bgInverse: Color.lerp(bgInverse, other.bgInverse, t)!,
      surface: Color.lerp(surface, other.surface, t)!,
      surface2: Color.lerp(surface2, other.surface2, t)!,
      surface3: Color.lerp(surface3, other.surface3, t)!,
      surface4: Color.lerp(surface4, other.surface4, t)!,
      surfaceInverse: Color.lerp(surfaceInverse, other.surfaceInverse, t)!,
      overlay: Color.lerp(overlay, other.overlay, t)!,
      overlaySoft: Color.lerp(overlaySoft, other.overlaySoft, t)!,
      glassNav: Color.lerp(glassNav, other.glassNav, t)!,
      textPrimary: Color.lerp(textPrimary, other.textPrimary, t)!,
      textSecondary: Color.lerp(textSecondary, other.textSecondary, t)!,
      textMuted: Color.lerp(textMuted, other.textMuted, t)!,
      textDisabled: Color.lerp(textDisabled, other.textDisabled, t)!,
      textInverse: Color.lerp(textInverse, other.textInverse, t)!,
      border: Color.lerp(border, other.border, t)!,
      borderStrong: Color.lerp(borderStrong, other.borderStrong, t)!,
      borderBrand: Color.lerp(borderBrand, other.borderBrand, t)!,
      focus: Color.lerp(focus, other.focus, t)!,
      success: Color.lerp(success, other.success, t)!,
      successSoft: Color.lerp(successSoft, other.successSoft, t)!,
      warning: Color.lerp(warning, other.warning, t)!,
      warningSoft: Color.lerp(warningSoft, other.warningSoft, t)!,
      error: Color.lerp(error, other.error, t)!,
      errorSoft: Color.lerp(errorSoft, other.errorSoft, t)!,
      errorHover: Color.lerp(errorHover, other.errorHover, t)!,
      info: Color.lerp(info, other.info, t)!,
      infoSoft: Color.lerp(infoSoft, other.infoSoft, t)!,
      confidenceHigh: Color.lerp(confidenceHigh, other.confidenceHigh, t)!,
      confidenceMedium: Color.lerp(confidenceMedium, other.confidenceMedium, t)!,
      confidenceLow: Color.lerp(confidenceLow, other.confidenceLow, t)!,
      confidenceHighSoft: Color.lerp(confidenceHighSoft, other.confidenceHighSoft, t)!,
      confidenceMediumSoft: Color.lerp(confidenceMediumSoft, other.confidenceMediumSoft, t)!,
      confidenceLowSoft: Color.lerp(confidenceLowSoft, other.confidenceLowSoft, t)!,
      catGrocery: Color.lerp(catGrocery, other.catGrocery, t)!,
      catRestaurant: Color.lerp(catRestaurant, other.catRestaurant, t)!,
      catUtility: Color.lerp(catUtility, other.catUtility, t)!,
      catPersonalService: Color.lerp(catPersonalService, other.catPersonalService, t)!,
      catSubscription: Color.lerp(catSubscription, other.catSubscription, t)!,
      catOther: Color.lerp(catOther, other.catOther, t)!,
      space0: lerpDouble(space0, other.space0, t)!,
      space0_5: lerpDouble(space0_5, other.space0_5, t)!,
      space1: lerpDouble(space1, other.space1, t)!,
      space1_5: lerpDouble(space1_5, other.space1_5, t)!,
      space2: lerpDouble(space2, other.space2, t)!,
      space3: lerpDouble(space3, other.space3, t)!,
      space4: lerpDouble(space4, other.space4, t)!,
      space5: lerpDouble(space5, other.space5, t)!,
      space6: lerpDouble(space6, other.space6, t)!,
      space8: lerpDouble(space8, other.space8, t)!,
      space10: lerpDouble(space10, other.space10, t)!,
      space12: lerpDouble(space12, other.space12, t)!,
      space16: lerpDouble(space16, other.space16, t)!,
      space20: lerpDouble(space20, other.space20, t)!,
      space24: lerpDouble(space24, other.space24, t)!,
      space32: lerpDouble(space32, other.space32, t)!,
      space40: lerpDouble(space40, other.space40, t)!,
      space48: lerpDouble(space48, other.space48, t)!,
      radiusV0: lerpDouble(radiusV0, other.radiusV0, t)!,
      radiusXs: lerpDouble(radiusXs, other.radiusXs, t)!,
      radiusSm: lerpDouble(radiusSm, other.radiusSm, t)!,
      radiusMd: lerpDouble(radiusMd, other.radiusMd, t)!,
      radiusLg: lerpDouble(radiusLg, other.radiusLg, t)!,
      radiusXl: lerpDouble(radiusXl, other.radiusXl, t)!,
      radiusPill: lerpDouble(radiusPill, other.radiusPill, t)!,
      radiusFull: lerpDouble(radiusFull, other.radiusFull, t)!,
      stroke0: lerpDouble(stroke0, other.stroke0, t)!,
      stroke1: lerpDouble(stroke1, other.stroke1, t)!,
      stroke2: lerpDouble(stroke2, other.stroke2, t)!,
      stroke3: lerpDouble(stroke3, other.stroke3, t)!,
      shadow0: BoxShadow.lerpList(shadow0, other.shadow0, t)!,
      shadow1: BoxShadow.lerpList(shadow1, other.shadow1, t)!,
      shadow2: BoxShadow.lerpList(shadow2, other.shadow2, t)!,
      shadow3: BoxShadow.lerpList(shadow3, other.shadow3, t)!,
      shadow4: BoxShadow.lerpList(shadow4, other.shadow4, t)!,
      shadow5: BoxShadow.lerpList(shadow5, other.shadow5, t)!,
      durationInstant: Duration(milliseconds: lerpDouble(durationInstant.inMilliseconds.toDouble(), other.durationInstant.inMilliseconds.toDouble(), t)!.round()),
      durationFast: Duration(milliseconds: lerpDouble(durationFast.inMilliseconds.toDouble(), other.durationFast.inMilliseconds.toDouble(), t)!.round()),
      durationBase: Duration(milliseconds: lerpDouble(durationBase.inMilliseconds.toDouble(), other.durationBase.inMilliseconds.toDouble(), t)!.round()),
      durationSlow: Duration(milliseconds: lerpDouble(durationSlow.inMilliseconds.toDouble(), other.durationSlow.inMilliseconds.toDouble(), t)!.round()),
      durationElaborate: Duration(milliseconds: lerpDouble(durationElaborate.inMilliseconds.toDouble(), other.durationElaborate.inMilliseconds.toDouble(), t)!.round()),
      easeStandard: t < 0.5 ? easeStandard : other.easeStandard,
      easeOut: t < 0.5 ? easeOut : other.easeOut,
      easeIn: t < 0.5 ? easeIn : other.easeIn,
      easeInOut: t < 0.5 ? easeInOut : other.easeInOut,
      easeSpring: t < 0.5 ? easeSpring : other.easeSpring,
      typeHero: TextStyle.lerp(typeHero, other.typeHero, t)!,
      typeV4xl: TextStyle.lerp(typeV4xl, other.typeV4xl, t)!,
      typeV3xl: TextStyle.lerp(typeV3xl, other.typeV3xl, t)!,
      typeV2xl: TextStyle.lerp(typeV2xl, other.typeV2xl, t)!,
      typeXl: TextStyle.lerp(typeXl, other.typeXl, t)!,
      typeLg: TextStyle.lerp(typeLg, other.typeLg, t)!,
      typeLgreg: TextStyle.lerp(typeLgreg, other.typeLgreg, t)!,
      typeMd: TextStyle.lerp(typeMd, other.typeMd, t)!,
      typeBody: TextStyle.lerp(typeBody, other.typeBody, t)!,
      typeBodyem: TextStyle.lerp(typeBodyem, other.typeBodyem, t)!,
      typeSm: TextStyle.lerp(typeSm, other.typeSm, t)!,
      typeSmem: TextStyle.lerp(typeSmem, other.typeSmem, t)!,
      typeXs: TextStyle.lerp(typeXs, other.typeXs, t)!,
      typeXsem: TextStyle.lerp(typeXsem, other.typeXsem, t)!,
      typeNano: TextStyle.lerp(typeNano, other.typeNano, t)!,
      fontDisplay: t < 0.5 ? fontDisplay : other.fontDisplay,
      fontText: t < 0.5 ? fontText : other.fontText,
      fontMono: t < 0.5 ? fontMono : other.fontMono,
    );
  }
}


AppTokens _buildLightTokens() => AppTokens(
  brand: Color(0xFF0071E3),
  brandHover: Color(0xFF0077ED),
  brandPressed: Color(0xFF006EDB),
  brandSoft: Color.fromRGBO(0, 113, 227, 0.10),
  brandContrast: Color(0xFFFFFFFF),
  link: Color(0xFF0066CC),
  bg: Color(0xFFF5F5F7),
  bgInverse: Color(0xFF000000),
  surface: Color(0xFFFFFFFF),
  surface2: Color(0xFFFAFAFC),
  surface3: Color(0xFFEDEDF2),
  surface4: Color(0xFFF5F5F7),
  surfaceInverse: Color(0xFF1D1D1F),
  overlay: Color.fromRGBO(0, 0, 0, 0.48),
  overlaySoft: Color.fromRGBO(210, 210, 215, 0.64),
  glassNav: Color.fromRGBO(0, 0, 0, 0.8),
  textPrimary: Color(0xFF1D1D1F),
  textSecondary: Color.fromRGBO(0, 0, 0, 0.8),
  textMuted: Color.fromRGBO(0, 0, 0, 0.56),
  textDisabled: Color.fromRGBO(0, 0, 0, 0.48),
  textInverse: Color(0xFFFFFFFF),
  border: Color.fromRGBO(0, 0, 0, 0.12),
  borderStrong: Color.fromRGBO(0, 0, 0, 0.22),
  borderBrand: Color(0xFF0071E3),
  focus: Color(0xFF0071E3),
  success: Color(0xFF00B74A),
  successSoft: Color.fromRGBO(0, 183, 74, 0.12),
  warning: Color(0xFFFF9500),
  warningSoft: Color.fromRGBO(255, 149, 0, 0.14),
  error: Color(0xFFFF3B30),
  errorSoft: Color.fromRGBO(255, 59, 48, 0.12),
  errorHover: Color(0xFFD70015),
  info: Color(0xFF007AFF),
  infoSoft: Color.fromRGBO(0, 122, 255, 0.10),
  confidenceHigh: Color(0xFF00B74A),
  confidenceMedium: Color(0xFFFF9500),
  confidenceLow: Color(0xFFFF3B30),
  confidenceHighSoft: Color.fromRGBO(0, 183, 74, 0.12),
  confidenceMediumSoft: Color.fromRGBO(255, 149, 0, 0.14),
  confidenceLowSoft: Color.fromRGBO(255, 59, 48, 0.12),
  catGrocery: Color(0xFF34A36B),
  catRestaurant: Color(0xFFD37C2B),
  catUtility: Color(0xFF3A7CBD),
  catPersonalService: Color(0xFF8450B8),
  catSubscription: Color(0xFF2A8A95),
  catOther: Color.fromRGBO(0, 0, 0, 0.56),
  space0: 0.0,
  space0_5: 2.0,
  space1: 4.0,
  space1_5: 6.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space5: 20.0,
  space6: 24.0,
  space8: 32.0,
  space10: 40.0,
  space12: 48.0,
  space16: 64.0,
  space20: 80.0,
  space24: 96.0,
  space32: 128.0,
  space40: 160.0,
  space48: 192.0,
  radiusV0: 0.0,
  radiusXs: 5.0,
  radiusSm: 8.0,
  radiusMd: 11.0,
  radiusLg: 12.0,
  radiusXl: 16.0,
  radiusPill: 980.0,
  radiusFull: double.infinity,
  stroke0: 0.0,
  stroke1: 1.0,
  stroke2: 2.0,
  stroke3: 3.0,
  shadow0: <BoxShadow>[],
  shadow1: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.22), offset: Offset(3.0, 5.0), blurRadius: 30.0, spreadRadius: 0.0)],
  shadow2: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.14), offset: Offset(0.0, 6.0), blurRadius: 20.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.06), offset: Offset(0.0, 2.0), blurRadius: 4.0, spreadRadius: 0.0)],
  shadow3: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.18), offset: Offset(0.0, 12.0), blurRadius: 32.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.08), offset: Offset(0.0, 4.0), blurRadius: 8.0, spreadRadius: 0.0)],
  shadow4: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.24), offset: Offset(0.0, 24.0), blurRadius: 48.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.10), offset: Offset(0.0, 8.0), blurRadius: 16.0, spreadRadius: 0.0)],
  shadow5: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.32), offset: Offset(0.0, 40.0), blurRadius: 80.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.14), offset: Offset(0.0, 12.0), blurRadius: 24.0, spreadRadius: 0.0)],
  durationInstant: Duration(milliseconds: 100),
  durationFast: Duration(milliseconds: 150),
  durationBase: Duration(milliseconds: 240),
  durationSlow: Duration(milliseconds: 320),
  durationElaborate: Duration(milliseconds: 480),
  easeStandard: Cubic(0.25, 0.1, 0.25, 1.0),
  easeOut: Cubic(0.25, 1.0, 0.5, 1.0),
  easeIn: Cubic(0.4, 0.0, 1.0, 1.0),
  easeInOut: Cubic(0.42, 0.0, 0.58, 1.0),
  easeSpring: Cubic(0.32, 0.72, 0.0, 1.0),
  typeHero: const TextStyle(fontSize: 56.0, fontWeight: FontWeight.w600, letterSpacing: -0.28, height: 1.07, fontFamily: 'Inter'),
  typeV4xl: const TextStyle(fontSize: 40.0, fontWeight: FontWeight.w600, letterSpacing: -0.4, height: 1.1, fontFamily: 'Inter'),
  typeV3xl: const TextStyle(fontSize: 34.08, fontWeight: FontWeight.w600, letterSpacing: -0.374, height: 1.18, fontFamily: 'Inter'),
  typeV2xl: const TextStyle(fontSize: 28.0, fontWeight: FontWeight.w400, letterSpacing: 0.196, height: 1.14, fontFamily: 'Inter'),
  typeXl: const TextStyle(fontSize: 24.0, fontWeight: FontWeight.w300, letterSpacing: 0.0, height: 1.5, fontFamily: 'Inter'),
  typeLg: const TextStyle(fontSize: 20.96, fontWeight: FontWeight.w700, letterSpacing: 0.231, height: 1.19, fontFamily: 'Inter'),
  typeLgreg: const TextStyle(fontSize: 20.96, fontWeight: FontWeight.w400, letterSpacing: 0.231, height: 1.19, fontFamily: 'Inter'),
  typeMd: const TextStyle(fontSize: 18.08, fontWeight: FontWeight.w300, letterSpacing: 0.0, height: 1.0, fontFamily: 'Inter'),
  typeBody: const TextStyle(fontSize: 16.96, fontWeight: FontWeight.w400, letterSpacing: -0.374, height: 1.47, fontFamily: 'Inter'),
  typeBodyem: const TextStyle(fontSize: 16.96, fontWeight: FontWeight.w600, letterSpacing: -0.374, height: 1.24, fontFamily: 'Inter'),
  typeSm: const TextStyle(fontSize: 14.08, fontWeight: FontWeight.w400, letterSpacing: -0.224, height: 1.43, fontFamily: 'Inter'),
  typeSmem: const TextStyle(fontSize: 14.08, fontWeight: FontWeight.w600, letterSpacing: -0.224, height: 1.29, fontFamily: 'Inter'),
  typeXs: const TextStyle(fontSize: 12.0, fontWeight: FontWeight.w400, letterSpacing: -0.12, height: 1.33, fontFamily: 'Inter'),
  typeXsem: const TextStyle(fontSize: 12.0, fontWeight: FontWeight.w600, letterSpacing: -0.12, height: 1.33, fontFamily: 'Inter'),
  typeNano: const TextStyle(fontSize: 10.08, fontWeight: FontWeight.w400, letterSpacing: -0.08, height: 1.47, fontFamily: 'Inter'),
  fontDisplay: 'Inter',
  fontText: 'Inter',
  fontMono: 'JetBrainsMono',
);

AppTokens _buildDarkTokens() => AppTokens(
  brand: Color(0xFF0A84FF),
  brandHover: Color(0xFF1F8FFF),
  brandPressed: Color(0xFF0071E3),
  brandSoft: Color.fromRGBO(10, 132, 255, 0.16),
  brandContrast: Color(0xFFFFFFFF),
  link: Color(0xFF2997FF),
  bg: Color(0xFF000000),
  bgInverse: Color(0xFFF5F5F7),
  surface: Color(0xFF1D1D1F),
  surface2: Color(0xFF272729),
  surface3: Color(0xFF28282A),
  surface4: Color(0xFF2A2A2D),
  surfaceInverse: Color(0xFFF5F5F7),
  overlay: Color.fromRGBO(0, 0, 0, 0.72),
  overlaySoft: Color.fromRGBO(58, 58, 60, 0.72),
  glassNav: Color.fromRGBO(0, 0, 0, 0.8),
  textPrimary: Color(0xFFF5F5F7),
  textSecondary: Color.fromRGBO(245, 245, 247, 0.86),
  textMuted: Color.fromRGBO(245, 245, 247, 0.56),
  textDisabled: Color.fromRGBO(245, 245, 247, 0.40),
  textInverse: Color(0xFF1D1D1F),
  border: Color.fromRGBO(255, 255, 255, 0.12),
  borderStrong: Color.fromRGBO(255, 255, 255, 0.22),
  borderBrand: Color(0xFF0A84FF),
  focus: Color(0xFF0A84FF),
  success: Color(0xFF30D158),
  successSoft: Color.fromRGBO(48, 209, 88, 0.22),
  warning: Color(0xFFFF9F0A),
  warningSoft: Color.fromRGBO(255, 159, 10, 0.22),
  error: Color(0xFFFF453A),
  errorSoft: Color.fromRGBO(255, 69, 58, 0.20),
  errorHover: Color(0xFFFF6961),
  info: Color(0xFF2997FF),
  infoSoft: Color.fromRGBO(41, 151, 255, 0.18),
  confidenceHigh: Color(0xFF30D158),
  confidenceMedium: Color(0xFFFF9F0A),
  confidenceLow: Color(0xFFFF453A),
  confidenceHighSoft: Color.fromRGBO(48, 209, 88, 0.22),
  confidenceMediumSoft: Color.fromRGBO(255, 159, 10, 0.22),
  confidenceLowSoft: Color.fromRGBO(255, 69, 58, 0.20),
  catGrocery: Color(0xFF4CC488),
  catRestaurant: Color(0xFFE09255),
  catUtility: Color(0xFF5B9DDC),
  catPersonalService: Color(0xFFA27AD0),
  catSubscription: Color(0xFF4FB3BD),
  catOther: Color.fromRGBO(245, 245, 247, 0.56),
  space0: 0.0,
  space0_5: 2.0,
  space1: 4.0,
  space1_5: 6.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space5: 20.0,
  space6: 24.0,
  space8: 32.0,
  space10: 40.0,
  space12: 48.0,
  space16: 64.0,
  space20: 80.0,
  space24: 96.0,
  space32: 128.0,
  space40: 160.0,
  space48: 192.0,
  radiusV0: 0.0,
  radiusXs: 5.0,
  radiusSm: 8.0,
  radiusMd: 11.0,
  radiusLg: 12.0,
  radiusXl: 16.0,
  radiusPill: 980.0,
  radiusFull: double.infinity,
  stroke0: 0.0,
  stroke1: 1.0,
  stroke2: 2.0,
  stroke3: 3.0,
  shadow0: <BoxShadow>[],
  shadow1: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.22), offset: Offset(3.0, 5.0), blurRadius: 30.0, spreadRadius: 0.0)],
  shadow2: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.14), offset: Offset(0.0, 6.0), blurRadius: 20.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.06), offset: Offset(0.0, 2.0), blurRadius: 4.0, spreadRadius: 0.0)],
  shadow3: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.18), offset: Offset(0.0, 12.0), blurRadius: 32.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.08), offset: Offset(0.0, 4.0), blurRadius: 8.0, spreadRadius: 0.0)],
  shadow4: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.24), offset: Offset(0.0, 24.0), blurRadius: 48.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.10), offset: Offset(0.0, 8.0), blurRadius: 16.0, spreadRadius: 0.0)],
  shadow5: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.32), offset: Offset(0.0, 40.0), blurRadius: 80.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.14), offset: Offset(0.0, 12.0), blurRadius: 24.0, spreadRadius: 0.0)],
  durationInstant: Duration(milliseconds: 100),
  durationFast: Duration(milliseconds: 150),
  durationBase: Duration(milliseconds: 240),
  durationSlow: Duration(milliseconds: 320),
  durationElaborate: Duration(milliseconds: 480),
  easeStandard: Cubic(0.25, 0.1, 0.25, 1.0),
  easeOut: Cubic(0.25, 1.0, 0.5, 1.0),
  easeIn: Cubic(0.4, 0.0, 1.0, 1.0),
  easeInOut: Cubic(0.42, 0.0, 0.58, 1.0),
  easeSpring: Cubic(0.32, 0.72, 0.0, 1.0),
  typeHero: const TextStyle(fontSize: 56.0, fontWeight: FontWeight.w600, letterSpacing: -0.28, height: 1.07, fontFamily: 'Inter'),
  typeV4xl: const TextStyle(fontSize: 40.0, fontWeight: FontWeight.w600, letterSpacing: -0.4, height: 1.1, fontFamily: 'Inter'),
  typeV3xl: const TextStyle(fontSize: 34.08, fontWeight: FontWeight.w600, letterSpacing: -0.374, height: 1.18, fontFamily: 'Inter'),
  typeV2xl: const TextStyle(fontSize: 28.0, fontWeight: FontWeight.w400, letterSpacing: 0.196, height: 1.14, fontFamily: 'Inter'),
  typeXl: const TextStyle(fontSize: 24.0, fontWeight: FontWeight.w300, letterSpacing: 0.0, height: 1.5, fontFamily: 'Inter'),
  typeLg: const TextStyle(fontSize: 20.96, fontWeight: FontWeight.w700, letterSpacing: 0.231, height: 1.19, fontFamily: 'Inter'),
  typeLgreg: const TextStyle(fontSize: 20.96, fontWeight: FontWeight.w400, letterSpacing: 0.231, height: 1.19, fontFamily: 'Inter'),
  typeMd: const TextStyle(fontSize: 18.08, fontWeight: FontWeight.w300, letterSpacing: 0.0, height: 1.0, fontFamily: 'Inter'),
  typeBody: const TextStyle(fontSize: 16.96, fontWeight: FontWeight.w400, letterSpacing: -0.374, height: 1.47, fontFamily: 'Inter'),
  typeBodyem: const TextStyle(fontSize: 16.96, fontWeight: FontWeight.w600, letterSpacing: -0.374, height: 1.24, fontFamily: 'Inter'),
  typeSm: const TextStyle(fontSize: 14.08, fontWeight: FontWeight.w400, letterSpacing: -0.224, height: 1.43, fontFamily: 'Inter'),
  typeSmem: const TextStyle(fontSize: 14.08, fontWeight: FontWeight.w600, letterSpacing: -0.224, height: 1.29, fontFamily: 'Inter'),
  typeXs: const TextStyle(fontSize: 12.0, fontWeight: FontWeight.w400, letterSpacing: -0.12, height: 1.33, fontFamily: 'Inter'),
  typeXsem: const TextStyle(fontSize: 12.0, fontWeight: FontWeight.w600, letterSpacing: -0.12, height: 1.33, fontFamily: 'Inter'),
  typeNano: const TextStyle(fontSize: 10.08, fontWeight: FontWeight.w400, letterSpacing: -0.08, height: 1.47, fontFamily: 'Inter'),
  fontDisplay: 'Inter',
  fontText: 'Inter',
  fontMono: 'JetBrainsMono',
);

AppTokens _buildClayTokens() => AppTokens(
  brand: Color(0xFF8FBF9F),
  brandHover: Color(0xFF7FB091),
  brandPressed: Color(0xFF6FA181),
  brandSoft: Color.fromRGBO(143, 191, 159, 0.16),
  brandContrast: Color(0xFF1A1A1A),
  link: Color(0xFF4A7A6B),
  bg: Color(0xFFFAF9F7),
  bgInverse: Color(0xFF1A1A1A),
  surface: Color(0xFFFFFFFF),
  surface2: Color(0xFFF2EFE8),
  surface3: Color(0xFFE8E4DB),
  surface4: Color(0xFFDDD7CC),
  surfaceInverse: Color(0xFF1A1A1A),
  overlay: Color.fromRGBO(26, 26, 26, 0.48),
  overlaySoft: Color.fromRGBO(242, 239, 232, 0.64),
  glassNav: Color.fromRGBO(26, 26, 26, 0.80),
  textPrimary: Color(0xFF1A1A1A),
  textSecondary: Color.fromRGBO(26, 26, 26, 0.70),
  textMuted: Color.fromRGBO(26, 26, 26, 0.50),
  textDisabled: Color.fromRGBO(26, 26, 26, 0.36),
  textInverse: Color(0xFFFAF9F7),
  border: Color.fromRGBO(26, 26, 26, 0.12),
  borderStrong: Color(0xFF1A1A1A),
  borderBrand: Color(0xFF8FBF9F),
  focus: Color(0xFF8FBF9F),
  success: Color(0xFF8FBF9F),
  successSoft: Color.fromRGBO(143, 191, 159, 0.16),
  warning: Color(0xFFF5D86E),
  warningSoft: Color.fromRGBO(245, 216, 110, 0.18),
  error: Color(0xFFE85D6A),
  errorSoft: Color.fromRGBO(232, 93, 106, 0.14),
  errorHover: Color(0xFFD34A57),
  info: Color(0xFF5B7FC9),
  infoSoft: Color.fromRGBO(91, 127, 201, 0.16),
  confidenceHigh: Color(0xFF8FBF9F),
  confidenceMedium: Color(0xFFF5D86E),
  confidenceLow: Color(0xFFE85D6A),
  confidenceHighSoft: Color.fromRGBO(143, 191, 159, 0.16),
  confidenceMediumSoft: Color.fromRGBO(245, 216, 110, 0.18),
  confidenceLowSoft: Color.fromRGBO(232, 93, 106, 0.14),
  catGrocery: Color(0xFF8FBF9F),
  catRestaurant: Color(0xFFEC7BB0),
  catUtility: Color(0xFF5B7FC9),
  catPersonalService: Color(0xFFB19CD9),
  catSubscription: Color(0xFF8470B0),
  catOther: Color.fromRGBO(26, 26, 26, 0.50),
  space0: 0.0,
  space0_5: 2.0,
  space1: 4.0,
  space1_5: 6.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space5: 20.0,
  space6: 24.0,
  space8: 32.0,
  space10: 40.0,
  space12: 48.0,
  space16: 64.0,
  space20: 80.0,
  space24: 96.0,
  space32: 128.0,
  space40: 160.0,
  space48: 192.0,
  radiusV0: 0.0,
  radiusXs: 8.0,
  radiusSm: 12.0,
  radiusMd: 16.0,
  radiusLg: 24.0,
  radiusXl: 40.0,
  radiusPill: 999.0,
  radiusFull: double.infinity,
  stroke0: 0.0,
  stroke1: 1.0,
  stroke2: 2.0,
  stroke3: 3.0,
  shadow0: <BoxShadow>[],
  shadow1: <BoxShadow>[BoxShadow(color: Color(0xFF1A1A1A), offset: Offset(-3.0, 3.0), blurRadius: 0.0, spreadRadius: 0.0)],
  shadow2: <BoxShadow>[],
  shadow3: <BoxShadow>[],
  shadow4: <BoxShadow>[],
  shadow5: <BoxShadow>[],
  durationInstant: Duration(milliseconds: 100),
  durationFast: Duration(milliseconds: 180),
  durationBase: Duration(milliseconds: 280),
  durationSlow: Duration(milliseconds: 400),
  durationElaborate: Duration(milliseconds: 600),
  easeStandard: Cubic(0.33, 1.0, 0.68, 1.0),
  easeOut: Cubic(0.33, 1.0, 0.68, 1.0),
  easeIn: Cubic(0.64, 0.0, 0.78, 0.0),
  easeInOut: Cubic(0.65, 0.0, 0.35, 1.0),
  easeSpring: Cubic(0.34, 1.56, 0.64, 1.0),
  typeHero: const TextStyle(fontSize: 56.0, fontWeight: FontWeight.w600, letterSpacing: -0.12, height: 1.07, fontFamily: 'Lora'),
  typeV4xl: const TextStyle(fontSize: 40.0, fontWeight: FontWeight.w600, letterSpacing: -0.08, height: 1.1, fontFamily: 'Lora'),
  typeV3xl: const TextStyle(fontSize: 34.08, fontWeight: FontWeight.w600, letterSpacing: 0.0, height: 1.18, fontFamily: 'Lora'),
  typeV2xl: const TextStyle(fontSize: 28.0, fontWeight: FontWeight.w400, letterSpacing: 0.0, height: 1.14, fontFamily: 'Lora'),
  typeXl: const TextStyle(fontSize: 24.0, fontWeight: FontWeight.w300, letterSpacing: 0.0, height: 1.5, fontFamily: 'Lora'),
  typeLg: const TextStyle(fontSize: 20.96, fontWeight: FontWeight.w700, letterSpacing: 0.0, height: 1.19, fontFamily: 'Lora'),
  typeLgreg: const TextStyle(fontSize: 20.96, fontWeight: FontWeight.w400, letterSpacing: 0.0, height: 1.19, fontFamily: 'Lora'),
  typeMd: const TextStyle(fontSize: 18.08, fontWeight: FontWeight.w300, letterSpacing: 0.0, height: 1.0, fontFamily: 'Lora'),
  typeBody: const TextStyle(fontSize: 16.96, fontWeight: FontWeight.w400, letterSpacing: 0.0, height: 1.47, fontFamily: 'Lora'),
  typeBodyem: const TextStyle(fontSize: 16.96, fontWeight: FontWeight.w600, letterSpacing: 0.0, height: 1.24, fontFamily: 'Lora'),
  typeSm: const TextStyle(fontSize: 14.08, fontWeight: FontWeight.w400, letterSpacing: 0.0, height: 1.43, fontFamily: 'Lora'),
  typeSmem: const TextStyle(fontSize: 14.08, fontWeight: FontWeight.w600, letterSpacing: 0.0, height: 1.29, fontFamily: 'Lora'),
  typeXs: const TextStyle(fontSize: 12.0, fontWeight: FontWeight.w400, letterSpacing: 0.0, height: 1.33, fontFamily: 'Lora'),
  typeXsem: const TextStyle(fontSize: 12.0, fontWeight: FontWeight.w600, letterSpacing: 0.0, height: 1.33, fontFamily: 'Lora'),
  typeNano: const TextStyle(fontSize: 10.08, fontWeight: FontWeight.w400, letterSpacing: 0.4, height: 1.47, fontFamily: 'Lora'),
  fontDisplay: 'Lora',
  fontText: 'Lora',
  fontMono: 'JetBrainsMono',
);

AppTokens _buildClayDarkTokens() => AppTokens(
  brand: Color(0xFFA5D1B2),
  brandHover: Color(0xFFB5D9C0),
  brandPressed: Color(0xFF95C1A2),
  brandSoft: Color.fromRGBO(165, 209, 178, 0.20),
  brandContrast: Color(0xFF161513),
  link: Color(0xFFA5D1B2),
  bg: Color(0xFF161513),
  bgInverse: Color(0xFFFAF9F7),
  surface: Color(0xFF211F1C),
  surface2: Color(0xFF2A2724),
  surface3: Color(0xFF332F2B),
  surface4: Color(0xFF3D3934),
  surfaceInverse: Color(0xFFFAF9F7),
  overlay: Color.fromRGBO(0, 0, 0, 0.72),
  overlaySoft: Color.fromRGBO(242, 239, 232, 0.18),
  glassNav: Color.fromRGBO(22, 21, 19, 0.82),
  textPrimary: Color(0xFFF2EFE8),
  textSecondary: Color.fromRGBO(242, 239, 232, 0.80),
  textMuted: Color.fromRGBO(242, 239, 232, 0.56),
  textDisabled: Color.fromRGBO(242, 239, 232, 0.36),
  textInverse: Color(0xFF161513),
  border: Color.fromRGBO(242, 239, 232, 0.14),
  borderStrong: Color(0xFFF2EFE8),
  borderBrand: Color(0xFFA5D1B2),
  focus: Color(0xFFA5D1B2),
  success: Color(0xFFA5D1B2),
  successSoft: Color.fromRGBO(165, 209, 178, 0.20),
  warning: Color(0xFFF2D882),
  warningSoft: Color.fromRGBO(242, 216, 130, 0.20),
  error: Color(0xFFF07B85),
  errorSoft: Color.fromRGBO(240, 123, 133, 0.20),
  errorHover: Color(0xFFF59AA2),
  info: Color(0xFF8FA6D9),
  infoSoft: Color.fromRGBO(143, 166, 217, 0.20),
  confidenceHigh: Color(0xFFA5D1B2),
  confidenceMedium: Color(0xFFF2D882),
  confidenceLow: Color(0xFFF07B85),
  confidenceHighSoft: Color.fromRGBO(165, 209, 178, 0.20),
  confidenceMediumSoft: Color.fromRGBO(242, 216, 130, 0.20),
  confidenceLowSoft: Color.fromRGBO(240, 123, 133, 0.20),
  catGrocery: Color(0xFFA5D1B2),
  catRestaurant: Color(0xFFF09BC7),
  catUtility: Color(0xFF8FA6D9),
  catPersonalService: Color(0xFFC4B3E0),
  catSubscription: Color(0xFFA08EC7),
  catOther: Color.fromRGBO(242, 239, 232, 0.56),
  space0: 0.0,
  space0_5: 2.0,
  space1: 4.0,
  space1_5: 6.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space5: 20.0,
  space6: 24.0,
  space8: 32.0,
  space10: 40.0,
  space12: 48.0,
  space16: 64.0,
  space20: 80.0,
  space24: 96.0,
  space32: 128.0,
  space40: 160.0,
  space48: 192.0,
  radiusV0: 0.0,
  radiusXs: 5.0,
  radiusSm: 8.0,
  radiusMd: 11.0,
  radiusLg: 12.0,
  radiusXl: 16.0,
  radiusPill: 980.0,
  radiusFull: double.infinity,
  stroke0: 0.0,
  stroke1: 1.0,
  stroke2: 2.0,
  stroke3: 3.0,
  shadow0: <BoxShadow>[],
  shadow1: <BoxShadow>[BoxShadow(color: Color(0xFFF2EFE8), offset: Offset(-3.0, 3.0), blurRadius: 0.0, spreadRadius: 0.0)],
  shadow2: <BoxShadow>[],
  shadow3: <BoxShadow>[],
  shadow4: <BoxShadow>[],
  shadow5: <BoxShadow>[],
  durationInstant: Duration(milliseconds: 100),
  durationFast: Duration(milliseconds: 150),
  durationBase: Duration(milliseconds: 240),
  durationSlow: Duration(milliseconds: 320),
  durationElaborate: Duration(milliseconds: 480),
  easeStandard: Cubic(0.25, 0.1, 0.25, 1.0),
  easeOut: Cubic(0.25, 1.0, 0.5, 1.0),
  easeIn: Cubic(0.4, 0.0, 1.0, 1.0),
  easeInOut: Cubic(0.42, 0.0, 0.58, 1.0),
  easeSpring: Cubic(0.32, 0.72, 0.0, 1.0),
  typeHero: const TextStyle(fontSize: 56.0, fontWeight: FontWeight.w600, letterSpacing: -0.28, height: 1.07, fontFamily: 'Lora'),
  typeV4xl: const TextStyle(fontSize: 40.0, fontWeight: FontWeight.w600, letterSpacing: -0.4, height: 1.1, fontFamily: 'Lora'),
  typeV3xl: const TextStyle(fontSize: 34.08, fontWeight: FontWeight.w600, letterSpacing: -0.374, height: 1.18, fontFamily: 'Lora'),
  typeV2xl: const TextStyle(fontSize: 28.0, fontWeight: FontWeight.w400, letterSpacing: 0.196, height: 1.14, fontFamily: 'Lora'),
  typeXl: const TextStyle(fontSize: 24.0, fontWeight: FontWeight.w300, letterSpacing: 0.0, height: 1.5, fontFamily: 'Lora'),
  typeLg: const TextStyle(fontSize: 20.96, fontWeight: FontWeight.w700, letterSpacing: 0.231, height: 1.19, fontFamily: 'Lora'),
  typeLgreg: const TextStyle(fontSize: 20.96, fontWeight: FontWeight.w400, letterSpacing: 0.231, height: 1.19, fontFamily: 'Lora'),
  typeMd: const TextStyle(fontSize: 18.08, fontWeight: FontWeight.w300, letterSpacing: 0.0, height: 1.0, fontFamily: 'Lora'),
  typeBody: const TextStyle(fontSize: 16.96, fontWeight: FontWeight.w400, letterSpacing: -0.374, height: 1.47, fontFamily: 'Lora'),
  typeBodyem: const TextStyle(fontSize: 16.96, fontWeight: FontWeight.w600, letterSpacing: -0.374, height: 1.24, fontFamily: 'Lora'),
  typeSm: const TextStyle(fontSize: 14.08, fontWeight: FontWeight.w400, letterSpacing: -0.224, height: 1.43, fontFamily: 'Lora'),
  typeSmem: const TextStyle(fontSize: 14.08, fontWeight: FontWeight.w600, letterSpacing: -0.224, height: 1.29, fontFamily: 'Lora'),
  typeXs: const TextStyle(fontSize: 12.0, fontWeight: FontWeight.w400, letterSpacing: -0.12, height: 1.33, fontFamily: 'Lora'),
  typeXsem: const TextStyle(fontSize: 12.0, fontWeight: FontWeight.w600, letterSpacing: -0.12, height: 1.33, fontFamily: 'Lora'),
  typeNano: const TextStyle(fontSize: 10.08, fontWeight: FontWeight.w400, letterSpacing: -0.08, height: 1.47, fontFamily: 'Lora'),
  fontDisplay: 'Lora',
  fontText: 'Lora',
  fontMono: 'JetBrainsMono',
);

AppTokens _buildNotionTokens() => AppTokens(
  brand: Color(0xFF0075DE),
  brandHover: Color(0xFF005BAB),
  brandPressed: Color(0xFF005BAB),
  brandSoft: Color.fromRGBO(0, 117, 222, 0.08),
  brandContrast: Color(0xFFFFFFFF),
  link: Color(0xFF0075DE),
  bg: Color(0xFFFFFFFF),
  bgInverse: Color(0xFF31302E),
  surface: Color(0xFFFFFFFF),
  surface2: Color(0xFFF6F5F4),
  surface3: Color(0xFFFAFAF9),
  surface4: Color(0xFFEDEDEB),
  surfaceInverse: Color(0xFF31302E),
  overlay: Color.fromRGBO(0, 0, 0, 0.40),
  overlaySoft: Color.fromRGBO(246, 245, 244, 0.72),
  glassNav: Color.fromRGBO(255, 255, 255, 0.92),
  textPrimary: Color.fromRGBO(0, 0, 0, 0.95),
  textSecondary: Color(0xFF615D59),
  textMuted: Color(0xFFA39E98),
  textDisabled: Color(0xFFA39E98),
  textInverse: Color(0xFFF5F5F4),
  border: Color.fromRGBO(0, 0, 0, 0.10),
  borderStrong: Color.fromRGBO(0, 0, 0, 0.16),
  borderBrand: Color(0xFF0075DE),
  focus: Color(0xFF097FE8),
  success: Color(0xFF1AAE39),
  successSoft: Color.fromRGBO(26, 174, 57, 0.12),
  warning: Color(0xFFDD5B00),
  warningSoft: Color.fromRGBO(221, 91, 0, 0.10),
  error: Color(0xFFC4002B),
  errorSoft: Color(0xFFFDF2F4),
  errorHover: Color(0xFF9C0023),
  info: Color(0xFF097FE8),
  infoSoft: Color(0xFFF2F9FF),
  confidenceHigh: Color(0xFF1AAE39),
  confidenceMedium: Color(0xFFDD5B00),
  confidenceLow: Color(0xFFC4002B),
  confidenceHighSoft: Color.fromRGBO(26, 174, 57, 0.12),
  confidenceMediumSoft: Color.fromRGBO(221, 91, 0, 0.12),
  confidenceLowSoft: Color.fromRGBO(196, 0, 43, 0.10),
  catGrocery: Color(0xFF8A5A00),
  catRestaurant: Color(0xFFA0216E),
  catUtility: Color(0xFF2A4A99),
  catPersonalService: Color(0xFF391C57),
  catSubscription: Color(0xFF2A9D99),
  catOther: Color(0xFF615D59),
  space0: 0.0,
  space0_5: 2.0,
  space1: 4.0,
  space1_5: 6.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space5: 20.0,
  space6: 24.0,
  space8: 32.0,
  space10: 40.0,
  space12: 48.0,
  space16: 64.0,
  space20: 80.0,
  space24: 96.0,
  space32: 128.0,
  space40: 160.0,
  space48: 192.0,
  radiusV0: 0.0,
  radiusXs: 4.0,
  radiusSm: 5.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusXl: 16.0,
  radiusPill: 9999.0,
  radiusFull: double.infinity,
  stroke0: 0.0,
  stroke1: 1.0,
  stroke2: 2.0,
  stroke3: 3.0,
  shadow0: <BoxShadow>[],
  shadow1: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.06), offset: Offset(0.0, 0.0), blurRadius: 0.0, spreadRadius: 1.0)],
  shadow2: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.04), offset: Offset(0.0, 4.0), blurRadius: 18.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.027), offset: Offset(0.0, 2.0), blurRadius: 7.8, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.02), offset: Offset(0.0, 0.8), blurRadius: 2.9, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.01), offset: Offset(0.0, 0.2), blurRadius: 1.0, spreadRadius: 0.0)],
  shadow3: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.01), offset: Offset(0.0, 1.0), blurRadius: 3.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.02), offset: Offset(0.0, 3.0), blurRadius: 7.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.02), offset: Offset(0.0, 7.0), blurRadius: 15.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.04), offset: Offset(0.0, 14.0), blurRadius: 28.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.05), offset: Offset(0.0, 23.0), blurRadius: 52.0, spreadRadius: 0.0)],
  shadow4: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.02), offset: Offset(0.0, 2.0), blurRadius: 6.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.03), offset: Offset(0.0, 8.0), blurRadius: 18.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.04), offset: Offset(0.0, 18.0), blurRadius: 36.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.05), offset: Offset(0.0, 30.0), blurRadius: 60.0, spreadRadius: 0.0)],
  shadow5: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.03), offset: Offset(0.0, 4.0), blurRadius: 10.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.04), offset: Offset(0.0, 12.0), blurRadius: 28.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.05), offset: Offset(0.0, 24.0), blurRadius: 56.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.06), offset: Offset(0.0, 48.0), blurRadius: 96.0, spreadRadius: 0.0)],
  durationInstant: Duration(milliseconds: 100),
  durationFast: Duration(milliseconds: 150),
  durationBase: Duration(milliseconds: 200),
  durationSlow: Duration(milliseconds: 240),
  durationElaborate: Duration(milliseconds: 320),
  easeStandard: Cubic(0.2, 0.0, 0.0, 1.0),
  easeOut: Cubic(0.2, 0.0, 0.0, 1.0),
  easeIn: Cubic(0.4, 0.0, 1.0, 1.0),
  easeInOut: Cubic(0.42, 0.0, 0.58, 1.0),
  easeSpring: Cubic(0.16, 1.0, 0.3, 1.0),
  typeHero: const TextStyle(fontSize: 56.0, fontWeight: FontWeight.w600, letterSpacing: -2.125, height: 1.07, fontFamily: 'iAWriterQuattroS'),
  typeV4xl: const TextStyle(fontSize: 40.0, fontWeight: FontWeight.w600, letterSpacing: -1.875, height: 1.1, fontFamily: 'iAWriterQuattroS'),
  typeV3xl: const TextStyle(fontSize: 34.08, fontWeight: FontWeight.w600, letterSpacing: -1.5, height: 1.18, fontFamily: 'iAWriterQuattroS'),
  typeV2xl: const TextStyle(fontSize: 28.0, fontWeight: FontWeight.w400, letterSpacing: -0.625, height: 1.14, fontFamily: 'iAWriterQuattroS'),
  typeXl: const TextStyle(fontSize: 24.0, fontWeight: FontWeight.w300, letterSpacing: -0.25, height: 1.5, fontFamily: 'iAWriterQuattroS'),
  typeLg: const TextStyle(fontSize: 20.96, fontWeight: FontWeight.w700, letterSpacing: -0.125, height: 1.19, fontFamily: 'iAWriterQuattroS'),
  typeLgreg: const TextStyle(fontSize: 20.96, fontWeight: FontWeight.w400, letterSpacing: -0.125, height: 1.19, fontFamily: 'iAWriterQuattroS'),
  typeMd: const TextStyle(fontSize: 18.08, fontWeight: FontWeight.w300, letterSpacing: 0.0, height: 1.0, fontFamily: 'iAWriterQuattroS'),
  typeBody: const TextStyle(fontSize: 16.96, fontWeight: FontWeight.w400, letterSpacing: 0.0, height: 1.47, fontFamily: 'iAWriterQuattroS'),
  typeBodyem: const TextStyle(fontSize: 16.96, fontWeight: FontWeight.w600, letterSpacing: 0.0, height: 1.24, fontFamily: 'iAWriterQuattroS'),
  typeSm: const TextStyle(fontSize: 14.08, fontWeight: FontWeight.w400, letterSpacing: 0.0, height: 1.43, fontFamily: 'iAWriterQuattroS'),
  typeSmem: const TextStyle(fontSize: 14.08, fontWeight: FontWeight.w600, letterSpacing: 0.0, height: 1.29, fontFamily: 'iAWriterQuattroS'),
  typeXs: const TextStyle(fontSize: 12.0, fontWeight: FontWeight.w400, letterSpacing: 0.0, height: 1.33, fontFamily: 'iAWriterQuattroS'),
  typeXsem: const TextStyle(fontSize: 12.0, fontWeight: FontWeight.w600, letterSpacing: 0.0, height: 1.33, fontFamily: 'iAWriterQuattroS'),
  typeNano: const TextStyle(fontSize: 10.08, fontWeight: FontWeight.w400, letterSpacing: 0.125, height: 1.47, fontFamily: 'iAWriterQuattroS'),
  fontDisplay: 'iAWriterQuattroS',
  fontText: 'iAWriterQuattroS',
  fontMono: 'iAWriterMonoS',
);

AppTokens _buildNotionDarkTokens() => AppTokens(
  brand: Color(0xFF62AEF0),
  brandHover: Color(0xFF7CBCF3),
  brandPressed: Color(0xFF4F9FE5),
  brandSoft: Color.fromRGBO(98, 174, 240, 0.16),
  brandContrast: Color(0xFF1A1A1A),
  link: Color(0xFF62AEF0),
  bg: Color(0xFF31302E),
  bgInverse: Color(0xFFFFFFFF),
  surface: Color(0xFF3A3937),
  surface2: Color(0xFF41403D),
  surface3: Color(0xFF000000) /* UNCONVERTIBLE token */,
  surface4: Color(0xFF535149),
  surfaceInverse: Color(0xFFFFFFFF),
  overlay: Color.fromRGBO(0, 0, 0, 0.64),
  overlaySoft: Color.fromRGBO(58, 57, 55, 0.72),
  glassNav: Color.fromRGBO(49, 48, 46, 0.92),
  textPrimary: Color(0xFFF5F5F4),
  textSecondary: Color.fromRGBO(245, 245, 244, 0.78),
  textMuted: Color.fromRGBO(245, 245, 244, 0.54),
  textDisabled: Color.fromRGBO(245, 245, 244, 0.36),
  textInverse: Color(0xFF1A1A1A),
  border: Color.fromRGBO(245, 245, 244, 0.14),
  borderStrong: Color.fromRGBO(245, 245, 244, 0.24),
  borderBrand: Color(0xFF62AEF0),
  focus: Color(0xFF62AEF0),
  success: Color(0xFF3EC45A),
  successSoft: Color.fromRGBO(62, 196, 90, 0.18),
  warning: Color(0xFFF08A40),
  warningSoft: Color.fromRGBO(240, 138, 64, 0.18),
  error: Color(0xFFF0586E),
  errorSoft: Color.fromRGBO(240, 88, 110, 0.16),
  errorHover: Color(0xFFF37388),
  info: Color(0xFF62AEF0),
  infoSoft: Color.fromRGBO(98, 174, 240, 0.18),
  confidenceHigh: Color(0xFF3EC45A),
  confidenceMedium: Color(0xFFF08A40),
  confidenceLow: Color(0xFFF0586E),
  confidenceHighSoft: Color.fromRGBO(62, 196, 90, 0.18),
  confidenceMediumSoft: Color.fromRGBO(240, 138, 64, 0.18),
  confidenceLowSoft: Color.fromRGBO(240, 88, 110, 0.16),
  catGrocery: Color(0xFFE0A955),
  catRestaurant: Color(0xFFE98EC0),
  catUtility: Color(0xFF7DA4E8),
  catPersonalService: Color(0xFFA994D3),
  catSubscription: Color(0xFF5DBCB6),
  catOther: Color.fromRGBO(245, 245, 244, 0.62),
  space0: 0.0,
  space0_5: 2.0,
  space1: 4.0,
  space1_5: 6.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space5: 20.0,
  space6: 24.0,
  space8: 32.0,
  space10: 40.0,
  space12: 48.0,
  space16: 64.0,
  space20: 80.0,
  space24: 96.0,
  space32: 128.0,
  space40: 160.0,
  space48: 192.0,
  radiusV0: 0.0,
  radiusXs: 4.0,
  radiusSm: 5.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusXl: 16.0,
  radiusPill: 9999.0,
  radiusFull: double.infinity,
  stroke0: 0.0,
  stroke1: 1.0,
  stroke2: 2.0,
  stroke3: 3.0,
  shadow0: <BoxShadow>[],
  shadow1: <BoxShadow>[BoxShadow(color: Color.fromRGBO(245, 245, 244, 0.08), offset: Offset(0.0, 0.0), blurRadius: 0.0, spreadRadius: 1.0)],
  shadow2: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.30), offset: Offset(0.0, 4.0), blurRadius: 18.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.24), offset: Offset(0.0, 2.0), blurRadius: 7.8, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.18), offset: Offset(0.0, 0.8), blurRadius: 2.9, spreadRadius: 0.0)],
  shadow3: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.16), offset: Offset(0.0, 1.0), blurRadius: 3.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.20), offset: Offset(0.0, 3.0), blurRadius: 7.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.24), offset: Offset(0.0, 7.0), blurRadius: 15.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.30), offset: Offset(0.0, 14.0), blurRadius: 28.0, spreadRadius: 0.0)],
  shadow4: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.20), offset: Offset(0.0, 2.0), blurRadius: 6.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.26), offset: Offset(0.0, 8.0), blurRadius: 18.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.32), offset: Offset(0.0, 18.0), blurRadius: 36.0, spreadRadius: 0.0)],
  shadow5: <BoxShadow>[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.24), offset: Offset(0.0, 4.0), blurRadius: 10.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.30), offset: Offset(0.0, 12.0), blurRadius: 28.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.36), offset: Offset(0.0, 24.0), blurRadius: 56.0, spreadRadius: 0.0)],
  durationInstant: Duration(milliseconds: 100),
  durationFast: Duration(milliseconds: 150),
  durationBase: Duration(milliseconds: 200),
  durationSlow: Duration(milliseconds: 240),
  durationElaborate: Duration(milliseconds: 320),
  easeStandard: Cubic(0.2, 0.0, 0.0, 1.0),
  easeOut: Cubic(0.2, 0.0, 0.0, 1.0),
  easeIn: Cubic(0.4, 0.0, 1.0, 1.0),
  easeInOut: Cubic(0.42, 0.0, 0.58, 1.0),
  easeSpring: Cubic(0.16, 1.0, 0.3, 1.0),
  typeHero: const TextStyle(fontSize: 56.0, fontWeight: FontWeight.w600, letterSpacing: -2.125, height: 1.07, fontFamily: 'iAWriterQuattroS'),
  typeV4xl: const TextStyle(fontSize: 40.0, fontWeight: FontWeight.w600, letterSpacing: -1.875, height: 1.1, fontFamily: 'iAWriterQuattroS'),
  typeV3xl: const TextStyle(fontSize: 34.08, fontWeight: FontWeight.w600, letterSpacing: -1.5, height: 1.18, fontFamily: 'iAWriterQuattroS'),
  typeV2xl: const TextStyle(fontSize: 28.0, fontWeight: FontWeight.w400, letterSpacing: -0.625, height: 1.14, fontFamily: 'iAWriterQuattroS'),
  typeXl: const TextStyle(fontSize: 24.0, fontWeight: FontWeight.w300, letterSpacing: -0.25, height: 1.5, fontFamily: 'iAWriterQuattroS'),
  typeLg: const TextStyle(fontSize: 20.96, fontWeight: FontWeight.w700, letterSpacing: -0.125, height: 1.19, fontFamily: 'iAWriterQuattroS'),
  typeLgreg: const TextStyle(fontSize: 20.96, fontWeight: FontWeight.w400, letterSpacing: -0.125, height: 1.19, fontFamily: 'iAWriterQuattroS'),
  typeMd: const TextStyle(fontSize: 18.08, fontWeight: FontWeight.w300, letterSpacing: 0.0, height: 1.0, fontFamily: 'iAWriterQuattroS'),
  typeBody: const TextStyle(fontSize: 16.96, fontWeight: FontWeight.w400, letterSpacing: 0.0, height: 1.47, fontFamily: 'iAWriterQuattroS'),
  typeBodyem: const TextStyle(fontSize: 16.96, fontWeight: FontWeight.w600, letterSpacing: 0.0, height: 1.24, fontFamily: 'iAWriterQuattroS'),
  typeSm: const TextStyle(fontSize: 14.08, fontWeight: FontWeight.w400, letterSpacing: 0.0, height: 1.43, fontFamily: 'iAWriterQuattroS'),
  typeSmem: const TextStyle(fontSize: 14.08, fontWeight: FontWeight.w600, letterSpacing: 0.0, height: 1.29, fontFamily: 'iAWriterQuattroS'),
  typeXs: const TextStyle(fontSize: 12.0, fontWeight: FontWeight.w400, letterSpacing: 0.0, height: 1.33, fontFamily: 'iAWriterQuattroS'),
  typeXsem: const TextStyle(fontSize: 12.0, fontWeight: FontWeight.w600, letterSpacing: 0.0, height: 1.33, fontFamily: 'iAWriterQuattroS'),
  typeNano: const TextStyle(fontSize: 10.08, fontWeight: FontWeight.w400, letterSpacing: 0.125, height: 1.47, fontFamily: 'iAWriterQuattroS'),
  fontDisplay: 'iAWriterQuattroS',
  fontText: 'iAWriterQuattroS',
  fontMono: 'iAWriterMonoS',
);


AppTokens appTokensFor(String name) {
  switch (name) {
    case 'light': return _buildLightTokens();
    case 'dark': return _buildDarkTokens();
    case 'clay': return _buildClayTokens();
    case 'clay-dark': return _buildClayDarkTokens();
    case 'notion': return _buildNotionTokens();
    case 'notion-dark': return _buildNotionDarkTokens();
    default:
      assert(() { debugPrint('appTokensFor: unknown theme \$name — using light'); return true; }());
      return _buildLightTokens();
  }
}

ThemeData appThemeDataFor(String name) {
  switch (name) {
    case 'light': return _buildThemeData(_buildLightTokens(), brightness: Brightness.light);
    case 'dark': return _buildThemeData(_buildDarkTokens(), brightness: Brightness.dark);
    case 'clay': return _buildThemeData(_buildClayTokens(), brightness: Brightness.light);
    case 'clay-dark': return _buildThemeData(_buildClayDarkTokens(), brightness: Brightness.dark);
    case 'notion': return _buildThemeData(_buildNotionTokens(), brightness: Brightness.light);
    case 'notion-dark': return _buildThemeData(_buildNotionDarkTokens(), brightness: Brightness.dark);
    default:
      return _buildThemeData(_buildLightTokens(), brightness: Brightness.light);
  }
}

ThemeData _buildThemeData(AppTokens t, {required Brightness brightness}) {
  final colorScheme = ColorScheme(
    brightness: brightness,
    primary: t.brand,
    onPrimary: t.brandContrast,
    secondary: t.info,
    onSecondary: t.brandContrast,
    error: t.error,
    onError: t.brandContrast,
    surface: t.surface,
    onSurface: t.textPrimary,
    background: t.bg,
    onBackground: t.textPrimary,
  );
  return ThemeData(
    useMaterial3: true,
    brightness: brightness,
    colorScheme: colorScheme,
    scaffoldBackgroundColor: t.bg,
    extensions: <ThemeExtension<dynamic>>[t],
    fontFamily: t.fontText,
  );
}
